name: devel
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26
  - pyside2=5.15
  - qtpy
  - sphinx
  - pytest
  - pytest-xvfb
  - sphinx_rtd_theme
  - requests
  - python-dateutil
  - pyinstaller
  - setuptools
  - certifi
  - pip
  - pip:
    - sphinx-prompt
    - pydocstyle
    - sounderpy
